/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuildingDetail: typeof import('./src/components/mapping/BuildingDetail.vue')['default']
    BuildingGradeFilter: typeof import('./src/components/mapping/BuildingGradeFilter.vue')['default']
    BuildingTypeFilter: typeof import('./src/components/mapping/BuildingTypeFilter.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ConnectivityFilter: typeof import('./src/components/mapping/ConnectivityFilter.vue')['default']
    FilterGroup: typeof import('./src/components/mapping/FilterGroup.vue')['default']
    FilterSidebar: typeof import('./src/components/mapping/FilterSidebar.vue')['default']
    InstallationFilter: typeof import('./src/components/mapping/InstallationFilter.vue')['default']
    LCDPresenceFilter: typeof import('./src/components/mapping/LCDPresenceFilter.vue')['default']
    LocationFilter: typeof import('./src/components/mapping/LocationFilter.vue')['default']
    MapCenterMarker: typeof import('./src/components/mapping/MapCenterMarker.vue')['default']
    MapRadiusCircle: typeof import('./src/components/mapping/MapRadiusCircle.vue')['default']
    MapView: typeof import('./src/components/mapping/MapView.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PlaceAutocomplete: typeof import('./src/components/poi/PlaceAutocomplete.vue')['default']
    PlaceDetail: typeof import('./src/components/mapping/PlaceDetail.vue')['default']
    POIFilter: typeof import('./src/components/mapping/POIFilter.vue')['default']
    PointList: typeof import('./src/components/poi/PointList.vue')['default']
    ProgressFilter: typeof import('./src/components/mapping/ProgressFilter.vue')['default']
    RadiusFilter: typeof import('./src/components/mapping/RadiusFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesPackageFilter: typeof import('./src/components/mapping/SalesPackageFilter.vue')['default']
    ScreenTypeFilter: typeof import('./src/components/mapping/ScreenTypeFilter.vue')['default']
    SellableFilter: typeof import('./src/components/mapping/SellableFilter.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    YearRangeFilter: typeof import('./src/components/mapping/YearRangeFilter.vue')['default']
  }
}
