export const routes = [
  { path: '/', redirect: '/dashboard' },
  {
    path: '/',
    component: () => import('@/layouts/default.vue'),
    children: [
      {
        path: 'dashboard',
        component: () => import('@/pages/dashboard.vue'),
      },
      {
        path: 'buildings',
        name: 'buildings',
        component: () => import('@/pages/buildings.vue'),
      },
      {
        path: 'buildings/:id/edit',
        name: 'building-edit',
        component: () => import('@/pages/building-form.vue'),
        meta: { permission: 'buildings.manage' },
      },
      {
        path: 'mapping',
        name: 'mapping',
        component: () => import('@/pages/mapping.vue'),
        meta: { layoutWrapperClasses: 'layout-mapping-page' },
      },
      {
        path: 'pois',
        name: 'pois',
        component: () => import('@/pages/pois.vue'),
      },
      {
        path: 'pois/new',
        name: 'poi-new',
        component: () => import('@/pages/poi-form.vue'),
        meta: { permission: 'pois.manage' },
      },
      {
        path: 'pois/:id/edit',
        name: 'poi-edit',
        component: () => import('@/pages/poi-form.vue'),
        meta: { permission: 'pois.manage' },
      },
      {
        path: 'sales-packages',
        name: 'sales-packages',
        component: () => import('@/pages/sales-packages.vue'),
      },
      {
        path: 'sales-packages/new',
        name: 'sales-package-new',
        component: () => import('@/pages/sales-package-form.vue'),
        meta: { permission: 'sales-packages.manage' },
      },
      {
        path: 'sales-packages/:id/edit',
        name: 'sales-package-edit',
        component: () => import('@/pages/sales-package-form.vue'),
        meta: { permission: 'sales-packages.manage' },
      },
      {
        path: 'building-restrictions',
        name: 'building-restrictions',
        component: () => import('@/pages/building-restrictions.vue'),
        meta: { permission: 'building-restrictions.view' },
      },
      {
        path: 'building-restrictions/new',
        name: 'building-restriction-new',
        component: () => import('@/pages/building-restriction-form.vue'),
        meta: { permission: 'building-restrictions.manage' },
      },
      {
        path: 'building-restrictions/:id/edit',
        name: 'building-restriction-edit',
        component: () => import('@/pages/building-restriction-form.vue'),
        meta: { permission: 'building-restrictions.manage' },
      },
      {
        path: 'categories',
        name: 'categories',
        component: () => import('@/pages/categories.vue'),
        meta: { permission: 'master-data.view' },
      },
      {
        path: 'categories/new',
        name: 'category-new',
        component: () => import('@/pages/category-form.vue'),
        meta: { permission: 'master-data.manage' },
      },
      {
        path: 'categories/:id/edit',
        name: 'category-edit',
        component: () => import('@/pages/category-form.vue'),
        meta: { permission: 'master-data.manage' },
      },
      {
        path: 'sub-categories',
        name: 'sub-categories',
        component: () => import('@/pages/sub-categories.vue'),
        meta: { permission: 'master-data.view' },
      },
      {
        path: 'sub-categories/new',
        name: 'sub-category-new',
        component: () => import('@/pages/sub-category-form.vue'),
        meta: { permission: 'master-data.manage' },
      },
      {
        path: 'sub-categories/:id/edit',
        name: 'sub-category-edit',
        component: () => import('@/pages/sub-category-form.vue'),
        meta: { permission: 'master-data.manage' },
      },
      {
        path: 'mother-brands',
        name: 'mother-brands',
        component: () => import('@/pages/mother-brands.vue'),
        meta: { permission: 'master-data.view' },
      },
      {
        path: 'mother-brands/new',
        name: 'mother-brand-new',
        component: () => import('@/pages/mother-brand-form.vue'),
        meta: { permission: 'master-data.manage' },
      },
      {
        path: 'mother-brands/:id/edit',
        name: 'mother-brand-edit',
        component: () => import('@/pages/mother-brand-form.vue'),
        meta: { permission: 'master-data.manage' },
      },
      {
        path: 'branches',
        name: 'branches',
        component: () => import('@/pages/branches.vue'),
        meta: { permission: 'master-data.view' },
      },
      {
        path: 'branches/new',
        name: 'branch-new',
        component: () => import('@/pages/branch-form.vue'),
        meta: { permission: 'master-data.manage' },
      },
      {
        path: 'branches/:id/edit',
        name: 'branch-edit',
        component: () => import('@/pages/branch-form.vue'),
        meta: { permission: 'master-data.manage' },
      },
      {
        path: 'users',
        name: 'users',
        component: () => import('@/pages/users.vue'),
        meta: { permission: 'users.view' },
      },
      {
        path: 'users/new',
        name: 'user-new',
        component: () => import('@/pages/user-form.vue'),
        meta: { permission: 'users.manage' },
      },
      {
        path: 'users/:id/edit',
        name: 'user-edit',
        component: () => import('@/pages/user-form.vue'),
        meta: { permission: 'users.manage' },
      },
    ],
  },
  {
    path: '/',
    component: () => import('@/layouts/blank.vue'),
    children: [
      {
        path: 'login',
        component: () => import('@/pages/admin-login.vue'),
      },
      {
        path: 'not-authorized',
        name: 'not-authorized',
        component: () => import('@/pages/not-authorized.vue'),
      },
      {
        path: '/:pathMatch(.*)*',
        component: () => import('@/pages/[...error].vue'),
      },
    ],
  },
]
